/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Chicken_Slice_Chicken_0.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chicken_Slice_Chicken_0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chicken_Slice_Chicken_0.geometry} material={materials.Chicken} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Chicken_Slice_Chicken_0.glb')
